# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDbJ7H3reK6VJPzsLZSRWPZ0ZspEAVf_
"""

!pip install langchain

from langchain.document_loaders import TextLoader

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain-community

from langchain.document_loaders import TextLoader

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain langchain-community

from langchain_community.document_loaders import TextLoader

from langchain_community.document_loaders import TextLoader

loader= TextLoader("nvda_news_1.txt")
df=loader.load()

df

!pip install unstructured libmagic python-magic python-magic-bin

from langchain_community.document_loaders import UnstructuredURLLoader



# Commented out IPython magic to ensure Python compatibility.
# %pip install -U unstructured

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain-community unstructured

from langchain_community.document_loaders import UnstructuredURLLoader

loader=UnstructuredURLLoader(urls=[
    "https://www.moneycontrol.com/news/business/tata-motors-mahindra-gain-certificates-for-production-linked-payouts-11281691.html",
"https://www.moneycontrol.com/news/business/tata-motors-launches-punch-icng-price-starts-at-rs-7-1-lakh-11098751.html",
"https://www.moneycontrol.com/news/business/stocks/buy-tata-motors-target-of-rs-743-kr-choksey-11080811.html"

])

data=loader.load()

data

#text splitting

!pip install -U langchain-community

!pip install -U langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

r_splitter=RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n" , " "],
    chunk_size=200,
    chunk_overlap=0
)

type(df)

chunks = []

for item in data:
    chunks.extend(r_splitter.split_documents(item))

len(chunks)

chunks=r_splitter.split_documents(df)
len(chunks)



for i in chunks:
  print(len(i.page_content))

for i in chunks:
  print(i)

first_split=chunks[0]
first_split

pip install -U sentence-transformers

from huggingface_hub import login

login()

!pip install -U sentence-transformers transformers huggingface_hub

import sentence_transformers
import huggingface_hub
import transformers

print("sentence-transformers:", sentence_transformers.__version__)
print("huggingface-hub:", huggingface_hub.__version__)
print("transformers:", transformers.__version__)

from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

texts = [chunk.page_content for chunk in chunks]

vectors = encoder.encode(texts)

print(vectors.shape)

vectors

dim=vectors[1]

dim

!pip install faiss-cpu

import faiss

index = faiss.IndexFlatL2(dim)
index

index.add(vectors)

search_query="NVIDIA Stock"
vec=encoder.encode(search_query)
vec.shape

import numpy as np
svec=np.array(vec).reshape(1,-1)
svec.shape

svec

dis, I=index.search(svec,k=2)
dis

print(dis)
print(I)



print("Number of df items:", len(df))
print("FAISS indices:", I)
print("First row:", I[0])

print("df items:", len(df))
print("vectors shape:", vectors.shape)
print("FAISS vectors:", index.ntotal)
print("FAISS indices:", I)

print("Number of vectors:", len(vectors))
print("FAISS index size:", index.ntotal)

results = [chunks[i] for i in I[0]]
for result in results:
    print(result.page_content)

pip install langchain-openai Collecting langchain-openai

!pip install -U langchain-openai

import os
import streamlit as st
import pickle
import time
from langchain import OpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS

from dotenv import load_dotenv
load_dotenv()  # take environment variables from .env (especially openai api key)

st.title("RockyBot: News Research Tool 📈")
st.sidebar.title("News Article URLs")

urls = []
for i in range(3):
    url = st.sidebar.text_input(f"URL {i+1}")
    urls.append(url)

process_url_clicked = st.sidebar.button("Process URLs")
file_path = "faiss_store_openai.pkl"

main_placeholder = st.empty()
llm = OpenAI(temperature=0.9, max_tokens=500)

if process_url_clicked:
    # load data
    loader = UnstructuredURLLoader(urls=urls)
    main_placeholder.text("Data Loading...Started...✅✅✅")
    data = loader.load()
    # split data
    text_splitter = RecursiveCharacterTextSplitter(
        separators=['\n\n', '\n', '.', ','],
        chunk_size=1000
    )
    main_placeholder.text("Text Splitter...Started...✅✅✅")
    docs = text_splitter.split_documents(data)
    # create embeddings and save it to FAISS index
    embeddings = OpenAIEmbeddings()
    vectorstore_openai = FAISS.from_documents(docs, embeddings)
    main_placeholder.text("Embedding Vector Started Building...✅✅✅")
    time.sleep(2)

    # Save the FAISS index to a pickle file
    with open(file_path, "wb") as f:
        pickle.dump(vectorstore_openai, f)

query = main_placeholder.text_input("Question: ")
if query:
    if os.path.exists(file_path):
        with open(file_path, "rb") as f:
            vectorstore = pickle.load(f)
            chain = RetrievalQAWithSourcesChain.from_llm(llm=llm, retriever=vectorstore.as_retriever())
            result = chain({"question": query}, return_only_outputs=True)
            # result will be a dictionary of this format --> {"answer": "", "sources": [] }
            st.header("Answer")
            st.write(result["answer"])

            # Display sources, if available
            sources = result.get("sources", "")
            if sources:
                st.subheader("Sources:")
                sources_list = sources.split("\n")  # Split the sources by newline
                for source in sources_list:
                    st.write(source)

!pip install -q streamlit



import os
import streamlit as st
import pickle
import time
from langchain import OpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS

from dotenv import load_dotenv
load_dotenv()  # take environment variables from .env (especially openai api key)

st.title("RockyBot: News Research Tool 📈")
st.sidebar.title("News Article URLs")

urls = []
for i in range(3):
    url = st.sidebar.text_input(f"URL {i+1}")
    urls.append(url)

process_url_clicked = st.sidebar.button("Process URLs")
file_path = "faiss_store_openai.pkl"

main_placeholder = st.empty()
llm = OpenAI(temperature=0.9, max_tokens=500)

if process_url_clicked:
    # load data
    loader = UnstructuredURLLoader(urls=urls)
    main_placeholder.text("Data Loading...Started...✅✅✅")
    data = loader.load()
    # split data
    text_splitter = RecursiveCharacterTextSplitter(
        separators=['\n\n', '\n', '.', ','],
        chunk_size=1000
    )
    main_placeholder.text("Text Splitter...Started...✅✅✅")
    docs = text_splitter.split_documents(data)
    # create embeddings and save it to FAISS index
    embeddings = OpenAIEmbeddings()
    vectorstore_openai = FAISS.from_documents(docs, embeddings)
    main_placeholder.text("Embedding Vector Started Building...✅✅✅")
    time.sleep(2)

    # Save the FAISS index to a pickle file
    with open(file_path, "wb") as f:
        pickle.dump(vectorstore_openai, f)

query = main_placeholder.text_input("Question: ")
if query:
    if os.path.exists(file_path):
        with open(file_path, "rb") as f:
            vectorstore = pickle.load(f)
            chain = RetrievalQAWithSourcesChain.from_llm(llm=llm, retriever=vectorstore.as_retriever())
            result = chain({"question": query}, return_only_outputs=True)
            # result will be a dictionary of this format --> {"answer": "", "sources": [] }
            st.header("Answer")
            st.write(result["answer"])

            # Display sources, if available
            sources = result.get("sources", "")
            if sources:
                st.subheader("Sources:")
                sources_list = sources.split("\n")  # Split the sources by newline
                for source in sources_list:
                    st.write(source)

!pip install -q streamlit sentence-transformers faiss-cpu transformers torch \
    langchain langchain-community beautifulsoup4 requests pyngrok

from google.colab import userdata

api_key = userdata.get("my_key")

print("API key loaded:", bool(api_key))



import os
import streamlit as st
import pickle
import time
from langchain_openai import ChatOpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS

from dotenv import load_dotenv
load_dotenv()  # take environment variables from .env (especially openai api key)

st.title("UrBot: News Research Tool 📈")
st.sidebar.title("News Article URLs")

urls = []
for i in range(3):
    url = st.sidebar.text_input(f"URL {i+1}")
    urls.append(url)

process_url_clicked = st.sidebar.button("Process URLs")
file_path = "faiss_store_openai.pkl"

main_placeholder = st.empty()
llm = llm = ChatOpenAI(
    model="gpt-5.5",
    temperature=0,
    max_tokens=500
)

if process_url_clicked:
    # load data
    loader = UnstructuredURLLoader(urls=urls)
    main_placeholder.text("Data Loading...Started...✅✅✅")
    data = loader.load()
    # split data
    text_splitter = RecursiveCharacterTextSplitter(
        separators=['\n\n', '\n', '.', ','],
        chunk_size=1000
    )
    main_placeholder.text("Text Splitter...Started...✅✅✅")
    docs = text_splitter.split_documents(data)
    # create embeddings and save it to FAISS index
    embeddings = OpenAIEmbeddings()
    vectorstore_openai = FAISS.from_documents(docs, embeddings)
    main_placeholder.text("Embedding Vector Started Building...✅✅✅")
    time.sleep(2)

    # Save the FAISS index to a pickle file
    with open(file_path, "wb") as f:
        pickle.dump(vectorstore_openai, f)

query = main_placeholder.text_input("Question: ")
if query:
    if os.path.exists(file_path):
        with open(file_path, "rb") as f:
            vectorstore = pickle.load(f)
            chain = RetrievalQAWithSourcesChain.from_llm(llm=llm, retriever=vectorstore.as_retriever())
            result = chain({"question": query}, return_only_outputs=True)
            # result will be a dictionary of this format --> {"answer": "", "sources": [] }
            st.header("Answer")
            st.write(result["answer"])

            # Display sources, if available
            sources = result.get("sources", "")
            if sources:
                st.subheader("Sources:")
                sources_list = sources.split("\n")  # Split the sources by newline
                for source in sources_list:
                    st.write(source)

!pip install -q langchain-openai langchain-community langchain-text-splitters unstructured

import os
import streamlit as st
import pickle
import time
from langchain_openai import OpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS

from dotenv import load_dotenv
load_dotenv()  # take environment variables from .env (especially openai api key)

st.title("RockyBot: News Research Tool 📈")
st.sidebar.title("News Article URLs")

urls = []
for i in range(3):
    url = st.sidebar.text_input(f"URL {i+1}")
    urls.append(url)

process_url_clicked = st.sidebar.button("Process URLs")
file_path = "faiss_store_openai.pkl"

main_placeholder = st.empty()
llm = OpenAI(temperature=0.9, max_tokens=500)

if process_url_clicked:
    # load data
    loader = UnstructuredURLLoader(urls=urls)
    main_placeholder.text("Data Loading...Started...✅✅✅")
    data = loader.load()
    # split data
    text_splitter = RecursiveCharacterTextSplitter(
        separators=['\n\n', '\n', '.', ','],
        chunk_size=1000
    )
    main_placeholder.text("Text Splitter...Started...✅✅✅")
    docs = text_splitter.split_documents(data)
    # create embeddings and save it to FAISS index
    embeddings = OpenAIEmbeddings()
    vectorstore_openai = FAISS.from_documents(docs, embeddings)
    main_placeholder.text("Embedding Vector Started Building...✅✅✅")
    time.sleep(2)

    # Save the FAISS index to a pickle file
    with open(file_path, "wb") as f:
        pickle.dump(vectorstore_openai, f)

query = main_placeholder.text_input("Question: ")
if query:
    if os.path.exists(file_path):
        with open(file_path, "rb") as f:
            vectorstore = pickle.load(f)
            chain = RetrievalQAWithSourcesChain.from_llm(llm=llm, retriever=vectorstore.as_retriever())
            result = chain({"question": query}, return_only_outputs=True)
            # result will be a dictionary of this format --> {"answer": "", "sources": [] }
            st.header("Answer")
            st.write(result["answer"])

            # Display sources, if available
            sources = result.get("sources", "")
            if sources:
                st.subheader("Sources:")
                sources_list = sources.split("\n")  # Split the sources by newline
                for source in sources_list:
                    st.write(source)

!pip install -q langchain-openai

import os
import streamlit as st
import pickle
import time
import faiss

from sentence_transformers import SentenceTransformer

from langchain_openai import ChatOpenAI
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import UnstructuredURLLoader
from langchain_core.prompts import ChatPromptTemplate

from dotenv import load_dotenv

load_dotenv()


# --------------------------------------------------
# STREAMLIT UI
# --------------------------------------------------

st.title("RockyBot: News Research Tool 📈")
st.sidebar.title("News Article URLs")

urls = []

for i in range(3):
    url = st.sidebar.text_input(f"URL {i+1}")
    urls.append(url)

process_url_clicked = st.sidebar.button("Process URLs")

file_path = "faiss_store.pkl"

main_placeholder = st.empty()


# --------------------------------------------------
# LLM
# --------------------------------------------------

llm = ChatOpenAI(
    model="gpt-5.5",
    temperature=0,
    max_tokens=500
)


# --------------------------------------------------
# SENTENCE TRANSFORMER
# --------------------------------------------------

encoder = SentenceTransformer("all-MiniLM-L6-v2")


# --------------------------------------------------
# PROMPT
# --------------------------------------------------

prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a helpful news research assistant.

Answer the question using only the provided context.

If the answer cannot be found in the context,
say that you don't know.

Context:
{context}
"""
    ),
    ("human", "{question}")
])


chain = prompt | llm


# --------------------------------------------------
# PROCESS URLS
# --------------------------------------------------

if process_url_clicked:

    # Remove empty URLs
    urls = [url for url in urls if url.strip()]

    if not urls:
        st.error("Please enter at least one URL.")
        st.stop()


    # --------------------------------------------------
    # 1. LOAD DATA
    # --------------------------------------------------

    main_placeholder.text(
        "Data Loading...Started...✅"
    )

    loader = UnstructuredURLLoader(urls=urls)

    data = loader.load()

    st.write("Documents loaded:", len(data))


    # --------------------------------------------------
    # 2. TEXT SPLITTING
    # --------------------------------------------------

    main_placeholder.text(
        "Text Splitting...Started...✅"
    )

    text_splitter = RecursiveCharacterTextSplitter(
        separators=["\n\n", "\n", ".", ","],
        chunk_size=1000,
        chunk_overlap=100
    )

    docs = text_splitter.split_documents(data)

    st.write("Number of chunks:", len(docs))


    # --------------------------------------------------
    # 3. CREATE EMBEDDINGS
    # --------------------------------------------------

    main_placeholder.text(
        "Creating Embeddings...Started...✅"
    )

    texts = [
        doc.page_content
        for doc in docs
    ]

    vectors = encoder.encode(
        texts,
        convert_to_numpy=True
    )

    st.write("Embedding shape:", vectors.shape)


    # --------------------------------------------------
    # 4. CREATE FAISS INDEX
    # --------------------------------------------------

    main_placeholder.text(
        "Building FAISS Index...Started...✅"
    )

    dimension = vectors.shape[1]

    index = faiss.IndexFlatL2(dimension)

    index.add(vectors)

    st.write("Vectors stored in FAISS:", index.ntotal)


    # --------------------------------------------------
    # 5. SAVE FAISS + DOCUMENTS
    # --------------------------------------------------

    with open(file_path, "wb") as f:

        pickle.dump(
            {
                "index": index,
                "docs": docs
            },
            f
        )


    main_placeholder.text(
        "Processing Complete! ✅"
    )

    time.sleep(1)

    main_placeholder.empty()


# --------------------------------------------------
# QUESTION
# --------------------------------------------------

query = st.text_input("Question:")


if query:

    if os.path.exists(file_path):


        # LOAD FAISS + DOCUMENTS


        with open(file_path, "rb") as f:

            data = pickle.load(f)


        index = data["index"]

        docs = data["docs"]


        # 6. CONVERT QUERY INTO VECTOR


        query_vector = encoder.encode(
            [query],
            convert_to_numpy=True
        )


        # 7. SEARCH FAISS


        D, I = index.search(
            query_vector,
            3
        )


        # 8. GET RELEVANT DOCUMENTS


        results = [
            docs[i]
            for i in I[0]
        ]


        # 9. CREATE CONTEXT


        context = "\n\n".join(
            doc.page_content
            for doc in results
        )
        # 10. SEND CONTEXT TO LLM

        response = chain.invoke({
            "context": context,
            "question": query
        })


        # --------------------------------------------------
        # ANSWER
        # --------------------------------------------------

        st.header("Answer")

        st.write(response.content)


        # --------------------------------------------------
        # SOURCES
        # --------------------------------------------------

        st.subheader("Sources:")

        sources = set()

        for doc in results:

            source = doc.metadata.get(
                "source",
                "Unknown source"
            )

            sources.add(source)


        for source in sources:

            st.write(source)

    else:

        st.warning(
            "Please process the URLs first."
        )

from google.colab import userdata
import os

api_key = userdata.get("my_key")

os.environ["OPEN_API_KEY"] = api_key

print("API key loaded:", bool(api_key))

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-5.5",
    temperature=0,
    max_tokens=500
)

response = llm.invoke("Say hello")

print(response.content)

!pip install -U langchain-google-genai

import os
import streamlit as st
import pickle
import time
import faiss

from sentence_transformers import SentenceTransformer

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import UnstructuredURLLoader
from langchain_core.prompts import ChatPromptTemplate

from dotenv import load_dotenv

load_dotenv()


# --------------------------------------------------
# STREAMLIT UI
# --------------------------------------------------

st.title("RockyBot: News Research Tool 📈")
st.sidebar.title("News Article URLs")

urls = []

for i in range(3):
    url = st.sidebar.text_input(f"URL {i+1}")
    urls.append(url)

process_url_clicked = st.sidebar.button("Process URLs")

file_path = "faiss_store.pkl"

main_placeholder = st.empty()


# --------------------------------------------------
# LLM
# --------------------------------------------------

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0,
    max_tokens=500
)


# --------------------------------------------------
# SENTENCE TRANSFORMER
# --------------------------------------------------

encoder = SentenceTransformer("all-MiniLM-L6-v2")


# --------------------------------------------------
# PROMPT
# --------------------------------------------------

prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a helpful news research assistant.

Answer the question using only the provided context.

If the answer cannot be found in the context,
say that you don't know.

Context:
{context}
"""
    ),
    ("human", "{question}")
])


chain = prompt | llm


# --------------------------------------------------
# PROCESS URLS
# --------------------------------------------------

if process_url_clicked:

    # Remove empty URLs
    urls = [url for url in urls if url.strip()]

    if not urls:
        st.error("Please enter at least one URL.")
        st.stop()


    # --------------------------------------------------
    # 1. LOAD DATA
    # --------------------------------------------------

    main_placeholder.text(
        "Data Loading...Started...✅"
    )

    loader = UnstructuredURLLoader(urls=urls)

    data = loader.load()

    st.write("Documents loaded:", len(data))


    # --------------------------------------------------
    # 2. TEXT SPLITTING
    # --------------------------------------------------

    main_placeholder.text(
        "Text Splitting...Started...✅"
    )

    text_splitter = RecursiveCharacterTextSplitter(
        separators=["\n\n", "\n", ".", ","],
        chunk_size=1000,
        chunk_overlap=100
    )

    docs = text_splitter.split_documents(data)

    st.write("Number of chunks:", len(docs))


    # --------------------------------------------------
    # 3. CREATE EMBEDDINGS
    # --------------------------------------------------

    main_placeholder.text(
        "Creating Embeddings...Started...✅"
    )

    texts = [
        doc.page_content
        for doc in docs
    ]

    vectors = encoder.encode(
        texts,
        convert_to_numpy=True
    )

    st.write("Embedding shape:", vectors.shape)


    # --------------------------------------------------
    # 4. CREATE FAISS INDEX
    # --------------------------------------------------

    main_placeholder.text(
        "Building FAISS Index...Started...✅"
    )

    dimension = vectors.shape[1]

    index = faiss.IndexFlatL2(dimension)

    index.add(vectors)

    st.write("Vectors stored in FAISS:", index.ntotal)


    # --------------------------------------------------
    # 5. SAVE FAISS + DOCUMENTS
    # --------------------------------------------------

    with open(file_path, "wb") as f:

        pickle.dump(
            {
                "index": index,
                "docs": docs
            },
            f
        )


    main_placeholder.text(
        "Processing Complete! ✅"
    )

    time.sleep(1)

    main_placeholder.empty()


# --------------------------------------------------
# QUESTION
# --------------------------------------------------

query = st.text_input("Question:")


if query:

    if os.path.exists(file_path):


        # LOAD FAISS + DOCUMENTS


        with open(file_path, "rb") as f:

            data = pickle.load(f)


        index = data["index"]

        docs = data["docs"]


        # 6. CONVERT QUERY INTO VECTOR


        query_vector = encoder.encode(
            [query],
            convert_to_numpy=True
        )


        # 7. SEARCH FAISS


        D, I = index.search(
            query_vector,
            3
        )


        # 8. GET RELEVANT DOCUMENTS


        results = [
            docs[i]
            for i in I[0]
        ]


        # 9. CREATE CONTEXT


        context = "\n\n".join(
            doc.page_content
            for doc in results
        )
        # 10. SEND CONTEXT TO LLM

        response = chain.invoke({
            "context": context,
            "question": query
        })


        # --------------------------------------------------
        # ANSWER
        # --------------------------------------------------

        st.header("Answer")

        st.write(response.content)


        # --------------------------------------------------
        # SOURCES
        # --------------------------------------------------

        st.subheader("Sources:")

        sources = set()

        for doc in results:

            source = doc.metadata.get(
                "source",
                "Unknown source"
            )

            sources.add(source)


        for source in sources:

            st.write(source)

    else:

        st.warning(
            "Please process the URLs first."
        )

!pip install -U langchain-google-genai

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    temperature=0
)

response = llm.invoke(
    "Explain FAISS in one sentence."
)

print(response.content)

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q faiss-cpu sentence-transformers langchain-text-splitters langchain-google-genai

!streamlit run app.py &>/content/streamlit.log &

!cat /content/streamlit.log

!pwd
!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("RockyBot: News Research Tool 📈")
# 
# st.write("Streamlit is working!")

!ls -l

!cat /content/streamlit.log

!pip install -q pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("3J0HRvPX34W6HIAHwtnDEOXeDOI_62aSr5q22pvewohu7N9wM")

public_url = ngrok.connect(8501)

print(public_url)

!streamlit run app.py > /content/streamlit.log 2>&1 &

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q langchain-community

from langchain_community.document_loaders import UnstructuredURLLoader

print("UnstructuredURLLoader imported successfully!")

from google.colab import userdata
import os

api_key = userdata.get("my_key")

os.environ["OPEN_API_KEY"] = api_key

print("API key loaded:", bool(api_key))

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q unstructured

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q unstructured beautifulsoup4 requests

import unstructured

print("unstructured installed successfully")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import os
# import pickle
# import faiss
# import streamlit as st
# 
# from sentence_transformers import SentenceTransformer
# 
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.document_loaders import UnstructuredURLLoader
# from langchain_core.prompts import ChatPromptTemplate
# 
# from dotenv import load_dotenv
# 
# load_dotenv()
# 
# 
# # ============================================================
# # PAGE
# # ============================================================
# 
# st.set_page_config(
#     page_title="RockyBot",
#     page_icon="📈"
# )
# 
# st.title("RockyBot: News Research Tool 📈")
# 
# 
# # ============================================================
# # SIDEBAR - URL INPUT
# # ============================================================
# 
# st.sidebar.title("News Article URLs")
# 
# urls = []
# 
# for i in range(3):
# 
#     url = st.sidebar.text_input(
#         f"URL {i + 1}"
#     )
# 
#     urls.append(url)
# 
# 
# process_url_clicked = st.sidebar.button(
#     "Process URLs"
# )
# 
# 
# # ============================================================
# # FILE
# # ============================================================
# 
# file_path = "faiss_store.pkl"
# 
# 
# # ============================================================
# # STATUS AREA
# # ============================================================
# 
# main_placeholder = st.empty()
# 
# 
# # ============================================================
# # SENTENCE TRANSFORMER
# # ============================================================
# 
# @st.cache_resource
# def load_encoder():
# 
#     return SentenceTransformer(
#         "all-MiniLM-L6-v2"
#     )
# 
# 
# encoder = load_encoder()
# 
# 
# # ============================================================
# # GEMINI
# # ============================================================
# 
# @st.cache_resource
# def load_llm():
# 
#     return ChatGoogleGenerativeAI(
#         model="gemini-3.6-flash",
#         max_tokens=500
#     )
# 
# 
# llm = load_llm()
# 
# 
# # ============================================================
# # PROMPT
# # ============================================================
# 
# prompt = ChatPromptTemplate.from_messages([
# 
#     (
#         "system",
#         """
# You are a helpful news research assistant.
# 
# Answer the question using ONLY the provided context.
# 
# If the answer cannot be found in the context,
# say that you don't know.
# 
# Context:
# 
# {context}
# """
#     ),
# 
#     (
#         "human",
#         "{question}"
#     )
# ])
# 
# 
# chain = prompt | llm
# 
# 
# # ============================================================
# # PROCESS URLS
# # ============================================================
# 
# if process_url_clicked:
# 
#     # Remove empty URLs
# 
#     urls = [
#         url for url in urls
#         if url.strip()
#     ]
# 
# 
#     if not urls:
# 
#         st.sidebar.error(
#             "Please enter at least one URL."
#         )
# 
#         st.stop()
# 
# 
#     # ========================================================
#     # 1. LOAD DATA
#     # ========================================================
# 
#     main_placeholder.text(
#         "1️⃣ Loading data..."
#     )
# 
#     loader = UnstructuredURLLoader(
#         urls=urls
#     )
# 
#     data = loader.load()
# 
#     st.success(
#         f"Documents loaded: {len(data)}"
#     )
# 
# 
#     # ========================================================
#     # 2. TEXT SPLITTING
#     # ========================================================
# 
#     main_placeholder.text(
#         "2️⃣ Splitting text into chunks..."
#     )
# 
#     text_splitter = RecursiveCharacterTextSplitter(
# 
#         separators=[
#             "\n\n",
#             "\n",
#             ".",
#             ",",
#             " "
#         ],
# 
#         chunk_size=200,
# 
#         chunk_overlap=0
#     )
# 
# 
#     chunks = text_splitter.split_documents(
#         data
#     )
# 
# 
#     if not chunks:
# 
#         st.error(
#             "No text chunks were created from the URLs."
#         )
# 
#         st.stop()
# 
# 
#     st.success(
#         f"Chunks created: {len(chunks)}"
#     )
# 
# 
#     # ========================================================
#     # SHOW FIRST CHUNK
#     # ========================================================
# 
#     with st.expander("View first chunk"):
# 
#         st.write(
#             chunks[0].page_content
#         )
# 
#         st.write(
#             "Characters:",
#             len(chunks[0].page_content)
#         )
# 
# 
#     # ========================================================
#     # 3. CREATE EMBEDDINGS
#     # ========================================================
# 
#     main_placeholder.text(
#         "3️⃣ Creating embeddings..."
#     )
# 
# 
#     texts = [
#         chunk.page_content
#         for chunk in chunks
#     ]
# 
# 
#     vectors = encoder.encode(
# 
#         texts,
# 
#         convert_to_numpy=True
#     )
# 
# 
#     st.write(
#         "Embedding shape:",
#         vectors.shape
#     )
# 
# 
#     # ========================================================
#     # 4. CREATE FAISS INDEX
#     # ========================================================
# 
#     main_placeholder.text(
#         "4️⃣ Building FAISS index..."
#     )
# 
# 
#     dimension = vectors.shape[1]
# 
# 
#     index = faiss.IndexFlatL2(
#         dimension
#     )
# 
# 
#     index.add(
#         vectors
#     )
# 
# 
#     st.success(
#         f"FAISS vectors stored: {index.ntotal}"
#     )
# 
# 
#     # ========================================================
#     # 5. SAVE FAISS + DOCUMENTS
#     # ========================================================
# 
#     with open(
#         file_path,
#         "wb"
#     ) as f:
# 
#         pickle.dump(
# 
#             {
#                 "index": index,
#                 "docs": chunks
#             },
# 
#             f
#         )
# 
# 
#     main_placeholder.success(
#         "Processing complete! ✅"
#     )
# 
# 
# # ============================================================
# # QUESTION
# # ============================================================
# 
# st.divider()
# 
# st.header("Ask a Question")
# 
# query = st.text_input(
#     "Question:",
#     placeholder="Example: What happened to Tata Motors?"
# )
# 
# 
# # ============================================================
# # RETRIEVAL
# # ============================================================
# 
# if query:
# 
#     # ========================================================
#     # CHECK FAISS FILE
#     # ========================================================
# 
#     if not os.path.exists(
#         file_path
#     ):
# 
#         st.warning(
#             "Please process the URLs first."
#         )
# 
#         st.stop()
# 
# 
#     # ========================================================
#     # LOAD FAISS + DOCUMENTS
#     # ========================================================
# 
#     with open(
#         file_path,
#         "rb"
#     ) as f:
# 
#         stored_data = pickle.load(f)
# 
# 
#     index = stored_data["index"]
# 
#     chunks = stored_data["docs"]
# 
# 
#     # ========================================================
#     # QUERY EMBEDDING
#     # ========================================================
# 
#     query_vector = encoder.encode(
# 
#         [query],
# 
#         convert_to_numpy=True
#     )
# 
# 
#     # ========================================================
#     # FAISS SEARCH
#     # ========================================================
# 
#     D, I = index.search(
# 
#         query_vector,
# 
#         3
#     )
# 
# 
#     # ========================================================
#     # RETRIEVE TOP 3 CHUNKS
#     # ========================================================
# 
#     results = [
# 
#         chunks[i]
# 
#         for i in I[0]
# 
#         if i != -1
#     ]
# 
# 
#     # ========================================================
#     # SHOW RETRIEVED CHUNKS
#     # ========================================================
# 
#     with st.expander(
#         "View retrieved chunks"
#     ):
# 
#         for i, result in zip(
#             I[0],
#             results
#         ):
# 
#             st.write(
#                 f"Chunk index: {i}"
#             )
# 
#             st.write(
#                 result.page_content
#             )
# 
#             st.write("---")
# 
# 
#     # ========================================================
#     # CREATE CONTEXT
#     # ========================================================
# 
#     context = "\n\n".join(
# 
#         result.page_content
# 
#         for result in results
#     )
# 
# 
#     # ========================================================
#     # SEND CONTEXT + QUESTION TO GEMINI
#     # ========================================================
# 
#     with st.spinner(
#         "Generating answer..."
#     ):
# 
#         response = chain.invoke({
# 
#             "context": context,
# 
#             "question": query
# 
#         })
# 
# 
#     # ========================================================
#     # EXTRACT ANSWER
#     # ========================================================
# 
#     content = response.content
# 
# 
#     if isinstance(
#         content,
#         list
#     ):
# 
#         answer = "\n".join(
# 
#             block.get(
#                 "text",
#                 ""
#             )
# 
#             for block in content
# 
#             if isinstance(
#                 block,
#                 dict
#             )
# 
#             and block.get(
#                 "type"
#             ) == "text"
# 
#         )
# 
#     else:
# 
#         answer = content
# 
# 
#     # ========================================================
#     # DISPLAY ANSWER
#     # ========================================================
# 
#     st.header(
#         "Answer"
#     )
# 
#     st.write(
#         answer
#     )
# 
# 
#     # ========================================================
#     # DISPLAY SOURCES
#     # ========================================================
# 
#     st.subheader(
#         "Sources"
#     )
# 
# 
#     sources = set()
# 
# 
#     for result in results:
# 
#         source = result.metadata.get(
# 
#             "source",
# 
#             "Unknown source"
# 
#         )
# 
#         sources.add(
#             source
#         )
# 
# 
#     for source in sources:
# 
#         st.write(
#             source
#         )

!pkill -f streamlit

!streamlit run app.py > /content/streamlit.log 2>&1 &



from pyngrok import ngrok


ngrok.set_auth_token("3J0HRvPX34W6HIAHwtnDEOXeDOI_62aSr5q22pvewohu7N9wM")

public_url = ngrok.connect(8501)

print(public_url)

from google.colab import userdata
import os

os.environ["GOOGLE_API_KEY"] = userdata.get("my_key")

print("Gemini key loaded:", bool(os.environ.get("GOOGLE_API_KEY")))

!pkill -f streamlit

!streamlit run app.py > /content/streamlit.log 2>&1 &

from pyngrok import ngrok

# See existing tunnels
print(ngrok.get_tunnels())

ngrok.kill()

public_url = ngrok.connect(8501)
print(public_url)

!pkill -f streamlit
!streamlit run app.py > /content/streamlit.log 2>&1 &

public_url = ngrok.connect(8501)
print(public_url)

